package com.example.planning_worker.utils.enums;

import lombok.Getter;

@Getter
public enum AuthorityCode {
    CREATE_NEW_USER("A-001"), VIEW_LIST_USERS("A-002"), DELETE_USER("A-003"), EDIT_USER("A-004"), ACTIVATE_USER("A-005"), DEACTIVATE_USER("A-006"), VIEW_USER_DETAILS("A-007"), CREATE_NEW_DEPARTMENT("A-008"), UPDATE_DEPARTMENT("A-009"), DELETE_DEPARTMENT("A-010"), CREATE_NEW_COST_TYPE("A-011"), DELETE_COST_TYPE("A-012"), UPDATE_COST_TYPE("A-013"), CREATE_NEW_POSITION("A-014"), UPDATE_POSITION("A-015"), DELETE_POSITION("A-016"), VIEW_POSITION("A-017"), CREATE_NEW_PROJECT("A-018"), UPDATE_PROJECT("A-019"), DELETE_PROJECT("A-020"), VIEW_PROJECT("A-021"), CREATE_NEW_SUPPLIER("A-022"), UPDATE_SUPPLIER("A-023"), DELETE_SUPPLIER("A-024"), VIEW_SUPPLIER("A-025"), CREATE_NEW_EXCHANGE("A-026"), UPDATE_EXCHANGE("A-027"), DELETE_EXCHANGE("A-028"), VIEW_EXCHANGE("A-029"), CREATE_NEW_CURRENCY("A-030"), UPDATE_CURRENCY("A-031"), DELETE_CURRENCY("A-032"), VIEW_CURRENCY("A-033"),
    CREATE_TERM("B-001"), EDIT_TERM("B-002"), VIEW_TERM("B-003"), START_TERM("B-004"), DELETE_TERM("B-005"),
    IMPORT_PLAN("C-001"), RE_UPLOAD_PLAN("C-002"), SUBMIT_PLAN_FOR_REVIEW("C-003"), DELETE_PLAN("C-004"), DOWNLOAD_PLAN("C-005"), APPROVE_PLAN("C-006"), VIEW_PLAN("C-007"),
    VIEW_REPORT("D-001"), DOWNLOAD_REPORT("D-002"), DELETE_REPORT("D-003"),
    VIEW_ANNUAL_REPORT("E-001"), DOWNLOAD_ANNUAL_REPORT("E-002");

    private final String value;

    AuthorityCode(String value) {
        this.value = value;
    }

}